

development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development

test:
  adapter: postgresql
  encoding: utf8
  database: sample_app_test

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
